Tender/Tender/Controllers/CategoryManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TenderApp.Services;
using TenderApp.Models.BusinessModels;
using TenderApp.Models.AdminViewModels;

namespace TenderApp.Controllers
{
    public class CategoryManageController : Controller
    {
        IRepository<Category> repository;
        public CategoryManageController(IRepository<Category> repos)
        {
            repository = repos;
        }
        public IActionResult Index()
        {
            ViewBag.Categories = repository;
            return View(repository);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = repository;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel category)
        {
            ViewBag.Categories = repository;

            if (ModelState.IsValid)
            {
                Category parent = repository.FirstOrDefault(x => x.CategoryId == category.ParentId);
                Category cat = new Category()
                {
                    Name = category.Name,
                    Description = category.Description,
                    Type = category.Type,
                    Parent = parent
                };
                repository.Add(cat);
                return RedirectToAction("Index");
            }
            return View(category);
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            ViewBag.Categories = repository;
            Category cat = repository.FirstOrDefault(x => x.CategoryId == Id);
            if (cat == null)
            {
                throw new ApplicationException($"Не получилось загрузить категорию с  ID '{Id}'.");
            }
            CategoryViewModel model = new CategoryViewModel()
            {
                Name = cat.Name,
                Description = cat.Description,
                Type = cat.Type,

            };
            if (cat.Parent != null)
                model.ParentId = cat.Parent.CategoryId;
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(CategoryViewModel category, int Id)
        {
            ViewBag.Categories = repository;
            string status = null;
            if (ModelState.IsValid)
            {
                status = "Категория обновлена";
                var cat = repository.FirstOrDefault(x => x.CategoryId == Id);
                if (cat == null)
                {
                    throw new ApplicationException($"Не получилось загрузить категорию с  ID '{Id}'.");
                }
                cat.Name = category.Name;
                cat.Type = category.Type;
                cat.Description = category.Description;
                var parent = repository.FirstOrDefault(x => x.CategoryId == category.ParentId);
                if (!parent.Children.Contains(cat))
                cat.Parent = parent;
                repository.Update(cat);
            }
            ViewData["Status"] = status ?? "Error произошла ошибка";
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {

            Category cat = repository.FirstOrDefault(x => x.CategoryId == Id);
            repository.Remove(cat);
            return RedirectToAction("Index");
            return View();
        }
    }
}

Tender/Tender/Views/CategoryManage/Add.cshtml
@using TenderApp.Models.AdminViewModels
@using TenderApp.Models.BusinessModels

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
    IEnumerable<Category> categories = ViewBag.Categories as IEnumerable<Category>;
}
@model CategoryViewModel
<h2>Add</h2>
<form asp-action="Add">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
    <label asp-for="Description" ></label>
    <textarea asp-for="Description" class="form-control"></textarea>
    <select asp-for="ParentId" class="custom-select">
        <option value="@null">Нет</option>
        @foreach(var cat in categories)
        {
            <option value="@cat.CategoryId">@cat.Name</option>
        }
    </select>
    <button class="btn btn-primary" type="submit">Добавить</button>
</form>

Tender/Tender/Views/CategoryManage/Create.cshtml
@using TenderApp.Models.AdminViewModels
@using TenderApp.Models.BusinessModels

@{
    ViewData["Title"] = "Создать категорию";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
    IEnumerable<Category> categories = ViewBag.Categories as IEnumerable<Category>;
}
@model CategoryViewModel
<h2>Создать категорию</h2>
<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">

        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div>
        <select asp-for="ParentId" class="custom-select">
            <option value="0">Нет</option>
            @foreach (var cat in categories)
            {
                <option value="@cat.CategoryId">@cat.Name</option>
            }
        </select>
        <span asp-validation-for="ParentId" class="text-danger"></span>
    </div>
    <button class="btn btn-primary" type="submit">Добавить</button>
</form>

Tender/Tender/Views/CategoryManage/Edit.cshtml
@using TenderApp.Models.AdminViewModels
@using TenderApp.Models.BusinessModels
@{
    ViewData["Title"] = "Редактирование категории";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
    IEnumerable<Category> categories = ViewBag.Categories;
    int id = Convert.ToInt16(Url.ActionContext.RouteData.Values["id"]);
}
@model CategoryViewModel
<h2>Редактирование категории</h2>

@Html.Partial("_StatusMessage", ViewData["Status"])

<form asp-action="Edit" asp-route-Id="@id" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" value="@Model.Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea value="@Model.Description" asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">

        <label asp-for="ParentId"></label>
        <select asp-for="ParentId" class="custom-select">
            <option value="0">Нет</option>
            @foreach (var cat in categories)
            {
                if (cat.CategoryId != id)
                {
                    string selected = (cat.Parent != null && cat.Parent.CategoryId == Model.ParentId) ? "selected" : "";
                    <option value="@cat.CategoryId" class="@selected">@cat.Name</option>
                }
            }
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Редактировать</button>
</form>

Tender/Tender/Views/CategoryManage/Index.cshtml
@using TenderApp.Models.BusinessModels;
@using TenderApp.App_Code;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
    TempData["CatTab"] = "";
    ViewBag.RenderedCats = new List<Category>();
}
@model IEnumerable<Category>
<h2>Управление категориями @Html.ActionLink("Добавить", "Create", "CategoryManage", null, null, null, null, new { @class = "btn btn-primary" })</h2>

@*@Html.Cat(Model)*@
<table class="table table-striped table-sm table-bordered text-center ">
    <thead>
        <tr class="text-center">
            <th>Название</th>
            <th colspan="2">Описание</th>
        </tr>
    </thead>
    <tbody>
        @Html.Partial("_CategoriesList", Model)
    </tbody>
</table>


@Html.Partial("_ConfrirmationMessagePartial", new Dictionary<string, string>() { { "Message", "Вы действительно хотите удалить категорию? Действие необратимо." }, { "ButtonText", "Удалить" } })

Tender/Tender/Views/CategoryManage/_CategoriesList.cshtml
@using TenderApp.Models.BusinessModels
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    List<Category> reneredcats = ViewBag.RenderedCats as List<Category>;
    string tab = TempData["CatTab"].ToString();
}
@model IEnumerable<Category>
@foreach (var cat in Model)
{
    @if (!reneredcats.Contains(cat))
    {
        <tr>
            <td class="text-left">@tab @cat.Name @Html.Partial("_RUDPartial", cat.CategoryId)</td>
            <td>@cat.Description </td>

           
        </tr>
        
        reneredcats.Add(cat);
        ViewBag.RenderedCats = reneredcats;
        @if (cat.Children != null && cat.Children.Count > 0)
        {
            TempData["CatTab"] = tab + "--";
            Html.RenderPartial("_CategoriesList", cat.Children);
        }
    }
    }