Tender/Tender/Models/BusinessModels/Sub.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace TenderApp.Models.BusinessModels
{
    public class Sub
    {
        public int SubId { get; set; }
        public string Name { get; set; }
        public SubType Type { get; set; }
        public int Priority { get; set; }
        public int SupGroupId { get; set; }
        public virtual SubGroup SubGroup { get; set; }
        public enum SubType { TextBox,TextArea,Image};
    }
}

Tender/Tender/Models/BusinessModels/SubGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace TenderApp.Models.BusinessModels
{
    public class SubGroup
    {
        public int SubGroupId { get; set; }
        public string Name { get; set; }
        public Type ForType { get; set; }
        public int Priority { get; set; }
        public virtual ICollection<Sub> Sub { get; set; }

        public enum Type
        {
            [Display(Name = "Отзывы")]
            Review,
            [Display(Name = "Предложения")]
            Application,
            [Display(Name = "Страницы")]
            Page,
            [Display(Name = "Организации")]
            Organization,
            [Display(Name = "Тендеры")]
            Tender,
            [Display(Name = "Тендеры")]
            Offer,
            [Display(Name = "Комментарии")]
            Comment,
            [Display(Name = "Посты")]
            Post
        }
    }
}

Tender/Tender/Models/SubsViewModels/SubGroupViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TenderApp.Models.BusinessModels;

namespace TenderApp.Models.SubsViewModels
{
    public class SubGroupViewModel
    {
        
        [HiddenInput(DisplayValue = false)]
        public int? SubGroupId { get; set; }
        public string Name { get; set; }
        public SubGroup.Type ForType { get; set; }
        public int Priority { get; set; }
        public List<Sub> Subs { get; set; }
    }
}

Tender/Tender/Models/SubsViewModels/SubViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TenderApp.Models.BusinessModels;

namespace TenderApp.Models.SubsViewModels
{
    public class SubViewModel
    {
        [HiddenInput(DisplayValue = false)]
        public int SubGroupId { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int? SubId { get; set; }
        public string Name { get; set; }
        public Sub.SubType Type { get; set; }
        public int Priority { get; set; }
    }
}

Tender/Tender/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using TenderApp.Models;
using TenderApp.Models.ManageViewModels;
using TenderApp.Services;
using Microsoft.AspNetCore.Authorization;
using TenderApp.Models.BusinessModels;
using Microsoft.Extensions.Logging;
using TenderApp.Models.AccountViewModels;
using TenderApp.Data;

namespace TenderApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        IRepository repository;
        readonly UserManager<ApplicationUser> _userManager;
        readonly SignInManager<ApplicationUser> _signInManager;
        readonly IEmailSender _emailSender;
        readonly ILogger _logger;
        [TempData]
        string StatusMessage { get; set; }
        public AdminController(UserManager<ApplicationUser> userManager,
                      SignInManager<ApplicationUser> signInManager, IEmailSender emailSender,
            ILogger<AccountController> logger,
            IRepository repos)
        {
            repository = repos;
            this._userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = logger;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(_userManager.Users);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {

            var user = await _userManager.FindByIdAsync(Id);
            if (user == null)
            {
                throw new ApplicationException($"Не получилось загрузить пользователя с  ID '{_userManager.GetUserId(User)}'.");
            }

            var model = new IndexViewModel
            {
                Username = user.UserName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                IsEmailConfirmed = user.EmailConfirmed,
                StatusMessage = StatusMessage
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                throw new ApplicationException($"Не получилось загрузить пользователя с ID '{_userManager.GetUserId(User)}'.");
            }

            var email = user.Email;
            if (model.Email != email)
            {
                var setEmailResult = await _userManager.SetEmailAsync(user, model.Email);
                if (!setEmailResult.Succeeded)
                {
                    throw new ApplicationException($"Непредвиденная ошибка при установке email для пользователя с ID '{user.Id}'.");
                }
            }

            var phoneNumber = user.PhoneNumber;
            if (model.PhoneNumber != phoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, model.PhoneNumber);
                if (!setPhoneResult.Succeeded)
                {
                    throw new ApplicationException($"Непредвиденная ошибка при установке телефона для пользователя ID '{user.Id}'.");
                }
            }

            StatusMessage = "Профиль обновлен";
            return RedirectToAction("Edit", new { Id = model.Id });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string Id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(Id);
            await _userManager.RemoveFromRolesAsync(user, await _userManager.GetRolesAsync(user));
            await _userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult AddUser()
        {
            return View();
        }
        
        
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.UserName, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("Пользователь создал новый аккаунт с паролем.");
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
                    await _emailSender.SendEmailConfirmationAsync(model.Email, callbackUrl);
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            // If we got this far, something failed, redisplay form
            return View(model);
        }
        public ActionResult Users()
        {
            return View(_userManager.Users);
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

Tender/Tender/Controllers/SubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TenderApp.Services;
using TenderApp.Models.BusinessModels;
using Microsoft.AspNetCore.Authorization;
using TenderApp.Models.AdminViewModels;
using TenderApp.Models.SubsViewModels;

namespace TenderApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class SubController : Controller
    {
        IRepository repository;
        public SubController(IRepository repos)
        {
            repository = repos;
        }
        // GET: Sub
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SubGroups(SubGroup.Type type)
        {         
            return View(repository.SubGroup.Where(x => x.ForType == type));
        }
        [HttpGet]
        public IActionResult CreateSub()
        {
            return View("CESub");
        }

        [HttpPost]
        public ActionResult CreateSub(SubViewModel subm)
        {
            if (ModelState.IsValid)
            {
                SubGroup group = repository.SubGroup.FirstOrDefault(s => s.SubGroupId == subm.SubGroupId);
                if (group != null)
                {
                    Sub sub = new Sub()
                    {
                        Name = subm.Name,
                        SubGroup = group,
                        Priority = subm.Priority,
                        Type = subm.Type
                    };
                    repository.Sub.Add(sub);
                    return Redirect("SubGroups");
                }
                throw new ApplicationException($"Не получилось загрузить группу с  ID '{subm.SubGroupId}'.");
            }
            return View("CESub", subm);
        }
        [HttpGet]
        public PartialViewResult EditSub(SubViewModel sub)
        {
            return PartialView("CreateSub", sub);
        }

        [HttpPost]
        public ActionResult EditSub(int Parent, Sub sub)
        {
            SubGroup group = repository.SubGroup.FirstOrDefault(s => s.SubGroupId == Parent);
            if (group != null)

            {
                repository.Sub.Update(sub);
            }

            return Redirect("ManageSubs");
        }

        [HttpPost]
        public ActionResult DeleteSub(int SubId)
        {
            Sub current = repository.Sub.FirstOrDefault(s => s.SubId == SubId);
            if (current != null)
                repository.Sub.Remove(current);
            return Redirect("SubGroups");
        }

        [HttpGet]
        public IActionResult CreateSubGroup()
        {
            return View("CESubGroup");
        }
       

        [HttpGet]
        public PartialViewResult EditSubGroup()
        {
            return PartialView("CreateSubGroup");
        }

        [HttpPost]
        public IActionResult EditSubGroup(SubGroupViewModel group)
        {
            if (ModelState.IsValid)
            {
                var editgroup = repository.SubGroup.FirstOrDefault(x => x.SubGroupId == group.SubGroupId);
                editgroup.Name = group.Name;
                editgroup.Priority = editgroup.Priority;
                editgroup.ForType = editgroup.ForType;
                repository.SubGroup.Update(editgroup);
                return Redirect("ManageSubs");
            }
            return View(group);
        }

       

        [HttpPost]
        public ActionResult CreateSubGroup(SubGroupViewModel group)
        {
            if (ModelState.IsValid)
            {
                SubGroup newgroup = new SubGroup()
                {
                    Name = group.Name,
                    Priority = group.Priority,
                    ForType = group.ForType

                };
                repository.SubGroup.Add(newgroup);
                return Redirect("SubGroups");

            }
            return View(group);
        }
        [HttpPost]
        public ActionResult DeleteSubGroup(int groupId)
        {
            SubGroup current = repository.SubGroup.FirstOrDefault(s => s.SubGroupId == groupId);
            if (current != null)
                repository.SubGroup.Remove(current);
            return Redirect("SubGroups");
        }
        
    }
}

Tender/Tender/Views/Sub/CESub.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

*@
@{
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
    string action = (Model == null) ? "CreateSub" : "EditSub";
    string text = (Model == null) ? "Добавить" : "Редактировать";
    int subgruopid = (Model == null) ? Convert.ToInt16(Context.Request.Query["SubGroupId"]) : Model.SubGroupId;
}
@using TenderApp.Models.SubsViewModels;
@model SubViewModel
<h2>@text поле</h2>
<form asp-action="@action">
    @*@Html.Hidden("Parent", Model != null ? Model.Group.SubGroupId : -1,new { id="SubParentId" })*@
    <input asp-for="SubGroupId" value="@subgruopid" hidden />
    <input asp-for="SubId" value="@Model?.SubId" hidden />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" value="@Model?.Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    @*@Html.GetEnumSelectList(Model.Type.GetType());*@
    <div class="form-group">
        <label asp-for="Type"></label>
        <select name="Type" id="SubType" class="custom-select">
            <option value="0" class="@Model?.Type==Sub.SubType.TextBox?selected:;">TextBox</option>
            <option value="1" class="@Model?.Type==Sub.SubType.TextArea?selected:;">TextArea</option>
            <option value="2" class="@Model?.Type==Sub.SubType.Image?selected:;">Image</option>
        </select>
        <span asp-validation-for="Type" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label asp-for="Priority"></label>
        <input asp-for="Priority" value="@Model?.Priority" class="form-control" />
        <span asp-validation-for="Priority" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">@text</button>
</form>

Tender/Tender/Views/Sub/CESubGroup.cshtml
@using TenderApp.Models.SubsViewModels
@using TenderApp.Models.BusinessModels

@model SubGroupViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
    SubGroup.Type t;
    if (!string.IsNullOrEmpty(Context.Request.Query["type"].ToString()))
    {
        t = (SubGroup.Type)Enum.Parse(typeof(SubGroup.Type), Context.Request.Query["type"].ToString());
    }
    else { t = Model.ForType; }
    string action = (Model==null) ? "CreateSubGroup":"EditSubGroup";
    string text = (Model == null) ? "Добавить" : "Редактировать";
}
<h2>@text  группу</h2>
@*@using (Html.BeginForm("CreateSubGroup","Admin"))*@
<form asp-action="@action">
    <input asp-for="SubGroupId" value="@Model?.SubGroupId" hidden />
    <input asp-for="ForType" value="@t" hidden/>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" value="@Model?.Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Priority"></label>
        <input asp-for="Priority" value="@Model?.Priority" class="form-control"/>
        <span asp-validation-for="Priority" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">@text</button>
</form>

Tender/Tender/Views/Sub/Index.cshtml
@using TenderApp.Models.BusinessModels

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
}
<h2>Управление мета-полями </h2>
<table class="table table-striped table-sm table-bordered text-center ">
    <thead>
        <tr class="text-center">
            <th>Название</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var value in @EnumHelper<SubGroup.Type>.GetValues(SubGroup.Type.Application))
        {
            <tr>
                <td>@Html.ActionLink(EnumHelper<SubGroup.Type>.GetDisplayValue(value), "SubGroups", "Sub",null,null,null,new { type = value },null)</td>
            </tr>
        }
    </tbody>
</table>

Tender/Tender/Views/Sub/ManageSubs.cshtml
@using TenderApp.Models.BusinessModels
@model IEnumerable<SubGroup>

@{
    ViewData["Title"] = "ManageSubs";
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
}

@foreach (SubGroup s in Model.OrderBy(S => -S.Priority))
{
    <div>
        <a class="btn btn-primary" data-toggle="collapse" href="#@s.Name" aria-expanded="false" aria-controls="collapseExample">
            @s.Name
        </a>
        <span>
            @{
                string text = s.ForType.ToString();
            }
            @text
        </span>
        <form asp-action="DeleteSubGroup">
            <input type="hidden" name="groupId" value="@s.SubGroupId" />
            <input type="submit" class="btn btn-primary" value="Удалить группу полей">
        </form>
    </div>

    <div class="collapse" id="@s.Name">
        <div class="card card-block">
            <table>
                @foreach(Sub sub in s.Subs.OrderBy(S=> -S.Priority))

                {
                    <tr>
                        <td>
                            @sub.Name
                        </td>
                        <td>
                            @{
                                string Text = "";
                                switch ((int)sub.Type)
                                {
                                    case 0: Text = "TextBox"; break;
                                    case 1: Text = "TextArea"; break;
                                    case 2: Text = "Image"; break;
                                }
                                Html.DisplayText(Text);
                            }
                        </td>
                        <td>
                            @Html.ActionLink("Удалить поле", "DeleteSub", "Admin", sub, new { @class = "btn btn-default" })
                            @Html.ActionLink("Редактировать поле", "EditSub", "Admin", sub, new { @class = "btn btn-default" })
                        </td>
                    </tr>
                                }
            </table>
            @*@Html.ActionLink("Добавить поле", "CreateSubFor", "Admin", s, new { @class = "btn btn-block btn-default btn-lg" })*@
            @Html.Hidden("SubGroupIdHidden", s.SubGroupId,new { @class="SubGroupIdHidden" })
            <button class="btn btn-block btn-default btn-lg CreateSubButton" type="button" data-toggle="collapse" data-target="#SubCreater" aria-expanded="false" aria-controls="SubCreater">Добавить поле</button>
        </div>
    </div>
                                }

<button class="btn btn-primary" type="button" id="SubGroupCreaterButton" data-toggle="collapse" data-target="#SubGroupCreater" aria-expanded="false" aria-controls="SubGroupCreater">Добавить группу полей</button>

<div id="SubGroupCreater" class="collapse">
    @Html.Partial("CreateSubGroup",new SubGroup())
</div>

<div id="SubCreater" class="collapse">
    @Html.Partial("CreateSub",new Sub())
</div>

Tender/Tender/Views/Sub/SubGroups.cshtml
@using TenderApp.Models.BusinessModels
@{
    ViewData["Title"] = "SubGroups";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
}
@model IEnumerable<SubGroup>
<h2>Редактирование групп</h2>

@foreach (var group in Model)
{
    var i = 0;
    <div id="accordion">
        <div class="card">
            <div class="card-header" id="heading-@i">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-@i" aria-expanded="true" aria-controls="collapse-@i">
                        @group.Name
                    </button>
                </h5>
                @Html.Partial("_RUDPartial", group.SubGroupId)
            </div>

            <div id="collapse-@i" class="collapse show" aria-labelledby="heading-@i" data-parent="#accordion">
                <div class="card-body">
                    @if (group.Sub != null)
                    {
                        foreach (var sub in group.Sub)
                        {
                            var j = 0;
                            <div id="accordion-1">
                                <div class="card">
                                    <div class="card-header" id="heading-@i-@j">
                                        <h5 class="mb-0">
                                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-@i-@j" aria-expanded="true" aria-controls="collapse-@i-@j">
                                                @sub.Name
                                            </button>
                                        </h5>
                                        @Html.Partial("_RUDPartial", sub.SubId)
                                    </div>

                                    <div id="collapse-@i-@j" class="collapse show" aria-labelledby="heading-@i-@j" data-parent="#accordion-1">
                                        <div class="card-body">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    @Html.ActionLink("Добавить поле", "CreateSub", "Sub", null, null, null, new { SubGroupId = group.SubGroupId }, new { @class = "btn btn-primary" })


                </div>
            </div>
        </div>
    </div>
    i++;
}
@Html.ActionLink("Добавить группу", "CreateSubGroup", "Sub", null, null, null, new { type = Context.Request.Query["type"] }, new { @class = "btn btn-primary" })

Tender/Tender/Views/Sub/_SubGroupPartial.cshtml
@{
    ViewData["Title"] = "_SubGroupPartial";
    Layout = "~/Views/Shared/Layouts/_AdminLayout.cshtml";
}

<h2>_SubGroupPartial</h2>