Tender/Tender/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TenderApp.Models;
using TenderApp.Models.ManageViewModels;
using TenderApp.Models.RoleViewModels;
using TenderApp.Services;
using System.ComponentModel.DataAnnotations;

namespace SciBuy.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleAdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleAdminController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> rolemanager)
        {
            _userManager = userManager;
            _roleManager = rolemanager;
        }

        public async  Task<ActionResult> Index()
        {
            Dictionary<IdentityRole, IList<ApplicationUser>> usersinroles = new Dictionary<IdentityRole, IList<ApplicationUser>>();
            foreach (IdentityRole role in _roleManager.Roles)
            {
                IList<ApplicationUser> users = await _userManager.GetUsersInRoleAsync(role.Name);
                usersinroles.Add(role, users);
            }
            return View(usersinroles);
        }

        public ActionResult Create()
        {
            return View();
        }
        public async Task<ActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            IList<ApplicationUser> Users = await _userManager.GetUsersInRoleAsync(role.Name);
            string[] memberIDs =  Users.Select(x => x.Id).ToArray();
            IEnumerable<ApplicationUser> members
                = _userManager.Users.Where(x => memberIDs.Any(y => y == x.Id));

            IEnumerable<ApplicationUser> nonMembers = _userManager.Users.Except(members);

            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);
                   
                    result = await _userManager.AddToRoleAsync(user, model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);

                    result = await _userManager.RemoveFromRoleAsync(user,
                    model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");

            }
            return View("Error", new string[] { "Роль не найдена" });
        }
        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result
                    = await _roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Роль не найдена" });
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

Tender/Tender/Views/RoleAdmin/Create.cshtml
@model string
@{
    ViewBag.Title = "Создание роли";
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
}

<h2>Создать роль</h2>
@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Название</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

Tender/Tender/Views/RoleAdmin/Edit.cshtml
@using TenderApp.Models.RoleViewModels
@model RoleEditModel
@{
    ViewBag.Title = "Изменить роль";
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
}

<h2>Изменить роль</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class="panel panel-primary">
        <div class="panel-heading">Добавить в роль <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="2">Все пользователи в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Добавить в роль</td>
                </tr>
                foreach (ApplicationUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Удалить из роли <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="2">Нет пользователей в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Удалить из роли</td>
                </tr>
                foreach (ApplicationUser user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

Tender/Tender/Views/RoleAdmin/Index.cshtml
@using TenderApp.Models
@model  Dictionary<IdentityRole, IList<ApplicationUser>>

@{
    ViewBag.Title = "Роли";
    Layout = "/Views/Shared/Layouts/_AdminLayout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">Roles</div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Пользователи</th>
            <th style="min-width: 150px"></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">Нет ролей</td>
            </tr>
        }
        else
        {
            foreach (IdentityRole role in Model.Keys)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        @if (Model[role] == null || Model[role].Count == 0)
                        {
                            @: Нет пользователей в этой роли
                    }
                        else
                        {
                            <p>
                                @string.Join(", ", Model[role].Select(x =>
                           x.UserName))
                        </p>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id },FormMethod.Post,null,new { id="delete" }))
                        {
                            @Html.ActionLink("Изменить", "Edit", new { id = role.Id },
                        new { @class = "btn btn-primary btn-xs", style = "float:left; margin-right:5px" })
                            <button class="btn btn-danger btn-xs needconfirm" type="submit">Удалить</button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })
@Html.Partial("_ConfrirmationMessagePartial", new Dictionary<string, string>() { { "Message", "Вы действительно хотите удалить роль?" }, { "ButtonText", "Удалить" } })